import os
from typing import Optional

from drunc.fsm.actions.utils import get_dotdrunc_json
from drunc.fsm.core import FSMAction
from drunc.fsm.exceptions import DotDruncJsonIncorrectFormat
from drunc.utils.utils import get_logger


class ElisaLogbook(FSMAction):
    def __init__(self):
        super().__init__(name="elisa-logbook")
        self.log = get_logger("controller.elisa-logbook")

        dotdrunc = get_dotdrunc_json()
        elisa_hardware: str | None = os.getenv("DUNEDAQ_ELISA_LOGBOOK_APPARATUS", None)
        default_elisa_logbook: bool = False

        if elisa_hardware == "unified_shell":
            self.log.debug(
                "You are using the unified_shell, which does not support ELisA logbook posting."
            )
            return
        if elisa_hardware is None:
            self.log.warning(
                "Environment variable DUNEDAQ_ELISA_LOGBOOK_APPARATUS is not set, "
                "defaulting to [yellow]pdsp[/yellow])."
            )
            default_elisa_logbook = True
            self.elisa_hardware = "pdsp"

        if dotdrunc["elisa_configuration"].get(self.elisa_hardware):
            try:
                ec = dotdrunc["elisa_configuration"][self.elisa_hardware]
                self.API_SOCKET = ec["socket"]
                self.API_USER = ec["user"]
                self.API_PASS = ec["password"]
            except KeyError as exc:
                err_msg: str = (
                    "Malformed ~/.drunc.json, missing a key in 'elisa_configuration' "
                    "in your ~/.drunc.json, or the entire 'elisa_configuration' section"
                )
                raise DotDruncJsonIncorrectFormat(err_msg) from exc
        else:
            err_msg: str = ""
            if default_elisa_logbook:
                err_msg = (
                    "You need to update your ~/.drunc.json: The default ELisA logbook "
                    "[yellow]pdsp[/yellow] does not have a configuration."
                )
            else:
                err_msg = (
                    "You need to update your ~/.drunc.json: you have specified an "
                    f"ELisA logbook ({self.elisa_hardware}) in your configuration, but your "
                    "current ~/.drunc.json doesn't support this one."
                )
            raise DotDruncJsonIncorrectFormat(err_msg) from None

        self.log.info(f"Using the following ELisA logbook '{self.elisa_hardware}'.")
        self.timeout = 5

    def post_start(
        self, _input_data: dict, _context, elisa_post: Optional[str] = None, **kwargs
    ):
        if self.elisa_hardware == "unified_shell":
            return
        text = ""
        self.thread_id = None  # Clear this value here, so that if it fails stop can't reply to an old message

        self.run_num = _input_data["run"]
        if elisa_post is not None:
            self.log.info(
                f"Adding the message:\n--------\n{elisa_post}\n--------\nto the logbook"
            )
            text += f"\n<p>{elisa_post}</p>"

        self.run_type = _input_data.get(
            "production_vs_test", "TEST"
        )  # This class won't exist in a test run, so we're adding this temporarily so that we can actually run the function
        text += f"Configuration: {_context.configuration.initial_data}"
        text += f"\nRetrieve configuration: http://np04-srv-017.cern.ch:30015/runregistry/getRunBlob/{_input_data['run']}"

        if elisa_post is not None and self.run_type.lower() != "prod":
            self.log.warning(
                "Your message will NOT be stored, as this is not a PROD run"
            )

        text += "\n<p>log automatically generated by DRunC.</p>"
        self.det_id = _context.configuration.db.get_dal(
            class_name="Session", uid=_context.configuration.oks_key.session
        ).detector_configuration.id
        title = f"Run {self.run_num} ({self.run_type}) started on {self.det_id}"
        data = {
            "author": _context.actor.get_user_name(),
            "title": title,
            "body": text,
            "command": "start",
            "systems": ["daq"],
        }
        self.log.warning(f"Attempting to publish to ELisA logbook...\n{data}")
        # url = f"{self.API_SOCKET}/v1/elisaLogbook/new_message/"
        # try:
        #     r = requests.post(url, auth=(self.API_USER, self.API_PASS), json=data)
        #     r.raise_for_status()
        #     response = r.json()
        #     self.thread_id = response["thread_id"]
        #     self.log.info(f"ELisA logbook: Sent message (ID{self.thread_id})")
        # except requests.HTTPError:
        #     error = f"of HTTP Error (maybe failed auth, maybe ill-formed post message, ...) using {__name__}"
        #     self.log.warning(CannotSendElisaMessage(error).message)
        # except requests.ConnectionError:
        #     error = (
        #         f"connection to {self.API_SOCKET} wasn't successful using {__name__}"
        #     )
        #     self.log.warning(CannotSendElisaMessage(error).message)
        # except requests.Timeout:
        #     error = f"connection to {self.API_SOCKET} timed out using {__name__}"
        #     self.log.warning(CannotSendElisaMessage(error).message)

        return _input_data

    def post_drain_dataflow(
        self, _input_data, _context, elisa_post: Optional[str] = None, **kwargs
    ):
        if self.elisa_hardware == "unified_shell":
            return
        text = ""
        if elisa_post is not None:
            self.log.info(
                f"Adding the message:\n--------\n{elisa_post}\n--------\nto the logbook"
            )
            text += f"\n<p>{elisa_post}</p>"

        text += f"Run {self.run_num} ({self.run_type}) stopped on {self.det_id}"
        text += "\n<p>log automatically generated by DRunC.</p>"
        title = "User comment"
        data = {
            "author": _context.actor.get_user_name(),
            "title": title,
            "body": text,
            "command": "stop",
            "systems": ["daq"],
            "id": self.thread_id,
        }
        self.log.warning(f"Attempting to publish to ELisA logbook...\n{data}")
        # url = f"{self.API_SOCKET}/v1/elisaLogbook/reply_to_message/"
        # try:
        #     r = requests.put(url, auth=(self.API_USER, self.API_PASS), json=data)
        #     r.raise_for_status()
        #     response = r.json()
        #     self.log.info(f"ELisA logbook: Sent message (ID{response['thread_id']})")
        # except requests.HTTPError:
        #     error = f"of HTTP Error (maybe failed auth, maybe ill-formed post message, ...) using {__name__}"
        #     self.log.warning(CannotSendElisaMessage(error).message)
        # except requests.ConnectionError:
        #     error = (
        #         f"connection to {self.API_SOCKET} wasn't successful using {__name__}"
        #     )
        #     self.log.warning(CannotSendElisaMessage(error).message)
        # except requests.Timeout:
        #     error = f"connection to {self.API_SOCKET} timed out using {__name__}"
        #     self.log.warning(CannotSendElisaMessage(error).message)

        return _input_data
