repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        name: Check linting with Ruff
        entry: ruff check .
        args: [--no-fix]
      - id: ruff-format
        name: Fix formatting with Ruff
        entry: ruff format
        types_or: [python]