[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "drunc"
description = "A flexible run control infrastructure for a distributed DAQ system"
version = "0.19.0"
readme = "docs/README.md"
requires-python = ">=3.10"
dependencies = [
    "click",
    "click-shell",
    "protobuf",
    "types-protobuf",
    "grpcio",
    "grpcio-status",
    "grpcio-tools",
    "types-grpcio",
    "gunicorn",
    "kafka-python",
    "nest-asyncio",
    "rich",
    "requests",
    "Flask",
    "Flask-RESTful",
    "sh",
    "kubernetes",
    "pytz",
    "psutil",
]

[project.optional-dependencies]
dev = ["ruff", "pre-commit", "pytest", "pytest-cov", "grpcio-testing", "grpcio==1.68.0"]
test = ["pytest", "pytest-cov", "grpcio-testing", "grpcio==1.68.0"]

[project.scripts]
fake_daq_application = "drunc.apps.fake_daqapp_rest:main"
drunc-controller = "drunc.apps.controller:main"
drunc-controller-shell = "drunc.apps.controller_shell:main"
drunc-process-manager = "drunc.apps.pm:main"
drunc-process-manager-shell = "drunc.apps.pm_shell:main"
drunc-session-manager = "drunc.apps.session_manager:main"
drunc-unified-shell = "drunc.apps.unified_shell:main"
drunc-fsm-tests = "drunc.tests.fsm:main"
application-registry-service = "drunc.apps.app_connectivity_server:main"
drunc-ssh-validator = "drunc.apps.ssh_validator:main"
drunc-ssh-doctor = "drunc.apps.ssh_doctor:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"drunc.data.process_manager" = ["*.json"]
"drunc.data.process_manager.schema" = ["*.json"]

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=drunc --cov=src/drunc tests/"

[tool.coverage.run]
source = ["drunc"]
omit = ["tests/*"]

# * See https://docs.astral.sh/ruff/rules/ for details on Ruff's linting options
[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # check for errors using PyFlakes
    "I",    # best practices for import calls
    "UP",   # suggestions for code modernization
    "RUF",  # build in Ruff warnings
    "R",    # refactoring suggestions
]
ignore = [
    "E501", # Don't enforce line lengths within a linting context
]
