[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0"]

[project]
description = "A flexible run control infrastructure for a distributed DAQ system"
name = "drunc"
readme = "docs/README.md"
requires-python = ">=3.10"
version = "1.1.4"

dependencies = [
  "click",
  "click-shell",
  "protobuf",
  "types-protobuf",
  "grpcio",
  "grpcio-status",
  "grpcio-tools",
  "types-grpcio",
  "gunicorn",
  "kafka-python",
  "nest-asyncio",
  "rich",
  "requests",
  "Flask",
  "Flask-RESTful",
  "sh",
  "kubernetes",
  "pytz",
  "psutil",
  "paramiko",
]

[project.optional-dependencies]
dev = ["ruff", "pre-commit", "pytest", "pytest-cov", "grpcio-testing", "grpcio==1.75", "grpcio-tools==1.75", "grpcio-status==1.75", "types-requests"]
prod = ["paramiko[gssapi]"]
test = ["pytest", "pytest-cov", "grpcio-testing", "grpcio==1.75", "grpcio-tools==1.75", "grpcio-status==1.75"]

[project.scripts]
application-registry-service = "drunc.apps.app_connectivity_server:main"
drunc-check-np0x-cluster = "drunc.apps.check_np0x_cluster:main"
drunc-check-np0x-hw = "drunc.apps.check_np0x_hw_status:main"
drunc-controller = "drunc.apps.controller:main"
drunc-controller-shell = "drunc.apps.controller_shell:main"
drunc-fsm-tests = "drunc.tests.fsm:main"
drunc-process-manager = "drunc.apps.pm:main"
drunc-process-manager-shell = "drunc.apps.pm_shell:main"
drunc-session-manager = "drunc.apps.session_manager:main"
drunc-setup-ssh-config = "drunc.apps.ssh_configurator:main"
drunc-ssh-doctor = "drunc.apps.ssh_doctor:main"
drunc-unified-shell = "drunc.apps.unified_shell:main"
fake_daq_application = "drunc.apps.fake_daqapp_rest:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"drunc.data.process_manager" = ["*.json"]
"drunc.data.process_manager.schema" = ["*.json"]

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=drunc --cov=src/drunc"
markers = [
  "grpc: marks tests for gRPC isolation (run with --test-grpc)",
  "paramiko: marks tests for paramiko isolation (run with --test-paramiko)",
]
testpaths = ["tests"]

[tool.coverage.run]
omit = ["tests/*"]
source = ["drunc"]

# * See https://docs.astral.sh/ruff/rules/ for details on Ruff's linting options
[tool.ruff.lint]
ignore = [
  "E501", # Don't enforce line lengths within a linting context
]
select = [
  "E", # pycodestyle errors
  "F", # check for errors using PyFlakes
  "I", # best practices for import calls
  "UP", # suggestions for code modernization
  "RUF", # build in Ruff warnings
  "R", # refactoring suggestions
]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_defs = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = false
disallow_any_unimported = true

show_error_codes = true
warn_unused_configs = true

# These overrides are because the library stubs dont exist and not on typeshed
[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["google.rpc.*"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["conffwk"]
