# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import process_manager_pb2 as process__manager__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in process_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagerServiceStub(object):
    """Service for Manager component
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeRequest = channel.unary_unary(
                '/ssh_manager_test.ManagerService/MakeRequest',
                request_serializer=process__manager__pb2.DummyRequest.SerializeToString,
                response_deserializer=process__manager__pb2.DummyResponse.FromString,
                _registered_method=True)
        self.boot = channel.unary_unary(
                '/ssh_manager_test.ManagerService/boot',
                request_serializer=process__manager__pb2.BootRequest.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstanceList.FromString,
                _registered_method=True)
        self.Kill = channel.unary_unary(
                '/ssh_manager_test.ManagerService/Kill',
                request_serializer=process__manager__pb2.KillRequest.SerializeToString,
                response_deserializer=process__manager__pb2.KillResponse.FromString,
                _registered_method=True)


class ManagerServiceServicer(object):
    """Service for Manager component
    """

    def MakeRequest(self, request, context):
        """Basic method for connectivity testing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def boot(self, request, context):
        """Boot other processes via the manager (copied from druncschema)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Method for graceful shutdown of the Manager service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeRequest,
                    request_deserializer=process__manager__pb2.DummyRequest.FromString,
                    response_serializer=process__manager__pb2.DummyResponse.SerializeToString,
            ),
            'boot': grpc.unary_unary_rpc_method_handler(
                    servicer.boot,
                    request_deserializer=process__manager__pb2.BootRequest.FromString,
                    response_serializer=process__manager__pb2.ProcessInstanceList.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=process__manager__pb2.KillRequest.FromString,
                    response_serializer=process__manager__pb2.KillResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssh_manager_test.ManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ssh_manager_test.ManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagerService(object):
    """Service for Manager component
    """

    @staticmethod
    def MakeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssh_manager_test.ManagerService/MakeRequest',
            process__manager__pb2.DummyRequest.SerializeToString,
            process__manager__pb2.DummyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def boot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssh_manager_test.ManagerService/boot',
            process__manager__pb2.BootRequest.SerializeToString,
            process__manager__pb2.ProcessInstanceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssh_manager_test.ManagerService/Kill',
            process__manager__pb2.KillRequest.SerializeToString,
            process__manager__pb2.KillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RootControllerServiceStub(object):
    """Service for RootController component (for testing connectivity to booted servers)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeRequest = channel.unary_unary(
                '/ssh_manager_test.RootControllerService/MakeRequest',
                request_serializer=process__manager__pb2.DummyRequest.SerializeToString,
                response_deserializer=process__manager__pb2.DummyResponse.FromString,
                _registered_method=True)
        self.Kill = channel.unary_unary(
                '/ssh_manager_test.RootControllerService/Kill',
                request_serializer=process__manager__pb2.KillRequest.SerializeToString,
                response_deserializer=process__manager__pb2.KillResponse.FromString,
                _registered_method=True)


class RootControllerServiceServicer(object):
    """Service for RootController component (for testing connectivity to booted servers)
    """

    def MakeRequest(self, request, context):
        """Basic method for connectivity testing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Method for graceful shutdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RootControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeRequest,
                    request_deserializer=process__manager__pb2.DummyRequest.FromString,
                    response_serializer=process__manager__pb2.DummyResponse.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=process__manager__pb2.KillRequest.FromString,
                    response_serializer=process__manager__pb2.KillResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssh_manager_test.RootControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ssh_manager_test.RootControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RootControllerService(object):
    """Service for RootController component (for testing connectivity to booted servers)
    """

    @staticmethod
    def MakeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssh_manager_test.RootControllerService/MakeRequest',
            process__manager__pb2.DummyRequest.SerializeToString,
            process__manager__pb2.DummyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssh_manager_test.RootControllerService/Kill',
            process__manager__pb2.KillRequest.SerializeToString,
            process__manager__pb2.KillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
