# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import test_pb2 as test__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagerServiceStub(object):
    """Service for Manager component
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeRequest = channel.unary_unary(
                '/drunc.tests.grpc_tree.ManagerService/MakeRequest',
                request_serializer=test__pb2.DummyRequest.SerializeToString,
                response_deserializer=test__pb2.DummyResponse.FromString,
                _registered_method=True)
        self.ReceiveUpdate = channel.unary_unary(
                '/drunc.tests.grpc_tree.ManagerService/ReceiveUpdate',
                request_serializer=test__pb2.UpdateRequest.SerializeToString,
                response_deserializer=test__pb2.UpdateResponse.FromString,
                _registered_method=True)


class ManagerServiceServicer(object):
    """Service for Manager component
    """

    def MakeRequest(self, request, context):
        """Basic method for connectivity testing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveUpdate(self, request, context):
        """Method for receiving updates from RootController
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeRequest,
                    request_deserializer=test__pb2.DummyRequest.FromString,
                    response_serializer=test__pb2.DummyResponse.SerializeToString,
            ),
            'ReceiveUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveUpdate,
                    request_deserializer=test__pb2.UpdateRequest.FromString,
                    response_serializer=test__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drunc.tests.grpc_tree.ManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drunc.tests.grpc_tree.ManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagerService(object):
    """Service for Manager component
    """

    @staticmethod
    def MakeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drunc.tests.grpc_tree.ManagerService/MakeRequest',
            test__pb2.DummyRequest.SerializeToString,
            test__pb2.DummyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drunc.tests.grpc_tree.ManagerService/ReceiveUpdate',
            test__pb2.UpdateRequest.SerializeToString,
            test__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RootControllerServiceStub(object):
    """Service for RootController component  
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeRequest = channel.unary_unary(
                '/drunc.tests.grpc_tree.RootControllerService/MakeRequest',
                request_serializer=test__pb2.DummyRequest.SerializeToString,
                response_deserializer=test__pb2.DummyResponse.FromString,
                _registered_method=True)
        self.ReceiveCommand = channel.unary_unary(
                '/drunc.tests.grpc_tree.RootControllerService/ReceiveCommand',
                request_serializer=test__pb2.CommandRequest.SerializeToString,
                response_deserializer=test__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ReceiveStatus = channel.unary_unary(
                '/drunc.tests.grpc_tree.RootControllerService/ReceiveStatus',
                request_serializer=test__pb2.StatusRequest.SerializeToString,
                response_deserializer=test__pb2.StatusResponse.FromString,
                _registered_method=True)


class RootControllerServiceServicer(object):
    """Service for RootController component  
    """

    def MakeRequest(self, request, context):
        """Basic method for connectivity testing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveCommand(self, request, context):
        """Method for receiving commands from Manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveStatus(self, request, context):
        """Method for receiving status from ChildControllers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RootControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeRequest,
                    request_deserializer=test__pb2.DummyRequest.FromString,
                    response_serializer=test__pb2.DummyResponse.SerializeToString,
            ),
            'ReceiveCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveCommand,
                    request_deserializer=test__pb2.CommandRequest.FromString,
                    response_serializer=test__pb2.CommandResponse.SerializeToString,
            ),
            'ReceiveStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveStatus,
                    request_deserializer=test__pb2.StatusRequest.FromString,
                    response_serializer=test__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drunc.tests.grpc_tree.RootControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drunc.tests.grpc_tree.RootControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RootControllerService(object):
    """Service for RootController component  
    """

    @staticmethod
    def MakeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drunc.tests.grpc_tree.RootControllerService/MakeRequest',
            test__pb2.DummyRequest.SerializeToString,
            test__pb2.DummyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drunc.tests.grpc_tree.RootControllerService/ReceiveCommand',
            test__pb2.CommandRequest.SerializeToString,
            test__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drunc.tests.grpc_tree.RootControllerService/ReceiveStatus',
            test__pb2.StatusRequest.SerializeToString,
            test__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChildControllerServiceStub(object):
    """Service for ChildController components
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeRequest = channel.unary_unary(
                '/drunc.tests.grpc_tree.ChildControllerService/MakeRequest',
                request_serializer=test__pb2.DummyRequest.SerializeToString,
                response_deserializer=test__pb2.DummyResponse.FromString,
                _registered_method=True)
        self.ReceiveInstruction = channel.unary_unary(
                '/drunc.tests.grpc_tree.ChildControllerService/ReceiveInstruction',
                request_serializer=test__pb2.InstructionRequest.SerializeToString,
                response_deserializer=test__pb2.InstructionResponse.FromString,
                _registered_method=True)


class ChildControllerServiceServicer(object):
    """Service for ChildController components
    """

    def MakeRequest(self, request, context):
        """Basic method for connectivity testing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveInstruction(self, request, context):
        """Method for receiving instructions from RootController
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChildControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeRequest,
                    request_deserializer=test__pb2.DummyRequest.FromString,
                    response_serializer=test__pb2.DummyResponse.SerializeToString,
            ),
            'ReceiveInstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveInstruction,
                    request_deserializer=test__pb2.InstructionRequest.FromString,
                    response_serializer=test__pb2.InstructionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drunc.tests.grpc_tree.ChildControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drunc.tests.grpc_tree.ChildControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChildControllerService(object):
    """Service for ChildController components
    """

    @staticmethod
    def MakeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drunc.tests.grpc_tree.ChildControllerService/MakeRequest',
            test__pb2.DummyRequest.SerializeToString,
            test__pb2.DummyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveInstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drunc.tests.grpc_tree.ChildControllerService/ReceiveInstruction',
            test__pb2.InstructionRequest.SerializeToString,
            test__pb2.InstructionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
