# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x07\x63ommand\"\x17\n\x07\x43ommand\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0f\x43ommandResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2S\n\x0f\x43ommandReceiver\x12@\n\x0e\x45xecuteCommand\x12\x10.command.Command\x1a\x18.command.CommandResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=26
  _COMMAND._serialized_end=49
  _COMMANDRESPONSE._serialized_start=51
  _COMMANDRESPONSE._serialized_end=85
  _COMMANDRECEIVER._serialized_start=87
  _COMMANDRECEIVER._serialized_end=170
# @@protoc_insertion_point(module_scope)
