import __future__
from __future__ import annotations
__all__: list[str] = ['absolute_import']
def _assign_attribute(attribute):
    ...
def _assign_relation(relation):
    ...
def _return_attribute(attribute, dalobj = None, value = None):
    ...
def _return_relation(relation, multi = False, data = None, dalobj = None, cache = None):
    ...
absolute_import: __future__._Feature  # value = _Feature((2, 5, 0, 'alpha', 1), (3, 0, 0, 'alpha', 0), 262144)
