"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

if sys.version_info >= (3, 11):
    from typing import Never as _Never
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import Never as _Never
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DummyRequest(_message.Message):
    """Basic request/response for connectivity testing"""

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    timestamp: _builtins.int
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
        timestamp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DummyRequest: _TypeAlias = DummyRequest  # noqa: Y015

@_typing.final
class DummyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REPLY_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    reply: _builtins.str
    timestamp: _builtins.int
    def __init__(
        self,
        *,
        reply: _builtins.str = ...,
        timestamp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reply", b"reply", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DummyResponse: _TypeAlias = DummyResponse  # noqa: Y015

@_typing.final
class Token(_message.Message):
    """Token message"""

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    token: _builtins.str
    def __init__(
        self,
        *,
        token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Token: _TypeAlias = Token  # noqa: Y015

@_typing.final
class ResponseFlag(_message.Message):
    """Response flag"""

    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    message: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseFlag: _TypeAlias = ResponseFlag  # noqa: Y015

@_typing.final
class ProcessUUID(_message.Message):
    """Process UUID"""

    DESCRIPTOR: _descriptor.Descriptor

    UUID_FIELD_NUMBER: _builtins.int
    uuid: _builtins.str
    def __init__(
        self,
        *,
        uuid: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["uuid", b"uuid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessUUID: _TypeAlias = ProcessUUID  # noqa: Y015

@_typing.final
class ProcessMetadata(_message.Message):
    """Process metadata"""

    DESCRIPTOR: _descriptor.Descriptor

    UUID_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    SESSION_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    HOSTNAME_FIELD_NUMBER: _builtins.int
    TREE_ID_FIELD_NUMBER: _builtins.int
    user: _builtins.str
    session: _builtins.str
    name: _builtins.str
    hostname: _builtins.str
    tree_id: _builtins.str
    @_builtins.property
    def uuid(self) -> Global___ProcessUUID: ...
    def __init__(
        self,
        *,
        uuid: Global___ProcessUUID | None = ...,
        user: _builtins.str = ...,
        session: _builtins.str | None = ...,
        name: _builtins.str = ...,
        hostname: _builtins.str = ...,
        tree_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_session", b"_session", "_tree_id", b"_tree_id", "session", b"session", "tree_id", b"tree_id", "uuid", b"uuid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_session", b"_session", "_tree_id", b"_tree_id", "hostname", b"hostname", "name", b"name", "session", b"session", "tree_id", b"tree_id", "user", b"user", "uuid", b"uuid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__session: _TypeAlias = _typing.Literal["session"]  # noqa: Y015
    _WhichOneofArgType__session: _TypeAlias = _typing.Literal["_session", b"_session"]  # noqa: Y015
    _WhichOneofReturnType__tree_id: _TypeAlias = _typing.Literal["tree_id"]  # noqa: Y015
    _WhichOneofArgType__tree_id: _TypeAlias = _typing.Literal["_tree_id", b"_tree_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__session) -> _WhichOneofReturnType__session | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__tree_id) -> _WhichOneofReturnType__tree_id | None: ...

Global___ProcessMetadata: _TypeAlias = ProcessMetadata  # noqa: Y015

@_typing.final
class ProcessRestriction(_message.Message):
    """Process restriction"""

    DESCRIPTOR: _descriptor.Descriptor

    ALLOWED_HOSTS_FIELD_NUMBER: _builtins.int
    ALLOWED_HOST_TYPES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def allowed_hosts(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def allowed_host_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        allowed_hosts: _abc.Iterable[_builtins.str] | None = ...,
        allowed_host_types: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowed_host_types", b"allowed_host_types", "allowed_hosts", b"allowed_hosts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessRestriction: _TypeAlias = ProcessRestriction  # noqa: Y015

@_typing.final
class ProcessDescription(_message.Message):
    """Process description"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StringList(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        VALUES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            values: _abc.Iterable[_builtins.str] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ExecAndArgs(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EXEC_FIELD_NUMBER: _builtins.int
        ARGS_FIELD_NUMBER: _builtins.int
        exec: _builtins.str
        @_builtins.property
        def args(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            exec: _builtins.str = ...,
            args: _abc.Iterable[_builtins.str] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["args", b"args", "exec", b"exec"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class EnvEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    METADATA_FIELD_NUMBER: _builtins.int
    ENV_FIELD_NUMBER: _builtins.int
    EXECUTABLE_AND_ARGUMENTS_FIELD_NUMBER: _builtins.int
    PROCESS_EXECUTION_DIRECTORY_FIELD_NUMBER: _builtins.int
    PROCESS_LOGS_PATH_FIELD_NUMBER: _builtins.int
    process_execution_directory: _builtins.str
    process_logs_path: _builtins.str
    @_builtins.property
    def metadata(self) -> Global___ProcessMetadata: ...
    @_builtins.property
    def env(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def executable_and_arguments(self) -> _containers.RepeatedCompositeFieldContainer[Global___ProcessDescription.ExecAndArgs]: ...
    def __init__(
        self,
        *,
        metadata: Global___ProcessMetadata | None = ...,
        env: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        executable_and_arguments: _abc.Iterable[Global___ProcessDescription.ExecAndArgs] | None = ...,
        process_execution_directory: _builtins.str = ...,
        process_logs_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["env", b"env", "executable_and_arguments", b"executable_and_arguments", "metadata", b"metadata", "process_execution_directory", b"process_execution_directory", "process_logs_path", b"process_logs_path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessDescription: _TypeAlias = ProcessDescription  # noqa: Y015

@_typing.final
class ProcessInstance(_message.Message):
    """Process instance"""

    DESCRIPTOR: _descriptor.Descriptor

    class _StatusCode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ProcessInstance._StatusCode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        RUNNING: ProcessInstance._StatusCode.ValueType  # 0
        DEAD: ProcessInstance._StatusCode.ValueType  # 1

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    RUNNING: ProcessInstance.StatusCode.ValueType  # 0
    DEAD: ProcessInstance.StatusCode.ValueType  # 1

    PROCESS_DESCRIPTION_FIELD_NUMBER: _builtins.int
    PROCESS_RESTRICTION_FIELD_NUMBER: _builtins.int
    STATUS_CODE_FIELD_NUMBER: _builtins.int
    RETURN_CODE_FIELD_NUMBER: _builtins.int
    UUID_FIELD_NUMBER: _builtins.int
    status_code: Global___ProcessInstance.StatusCode.ValueType
    return_code: _builtins.int
    @_builtins.property
    def process_description(self) -> Global___ProcessDescription: ...
    @_builtins.property
    def process_restriction(self) -> Global___ProcessRestriction: ...
    @_builtins.property
    def uuid(self) -> Global___ProcessUUID: ...
    def __init__(
        self,
        *,
        process_description: Global___ProcessDescription | None = ...,
        process_restriction: Global___ProcessRestriction | None = ...,
        status_code: Global___ProcessInstance.StatusCode.ValueType = ...,
        return_code: _builtins.int = ...,
        uuid: Global___ProcessUUID | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "uuid", b"uuid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "return_code", b"return_code", "status_code", b"status_code", "uuid", b"uuid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessInstance: _TypeAlias = ProcessInstance  # noqa: Y015

@_typing.final
class ProcessInstanceList(_message.Message):
    """Process instance list"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TOKEN_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    FLAG_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def token(self) -> Global___Token: ...
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[Global___ProcessInstance]: ...
    @_builtins.property
    def flag(self) -> Global___ResponseFlag: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        token: Global___Token | None = ...,
        values: _abc.Iterable[Global___ProcessInstance] | None = ...,
        flag: Global___ResponseFlag | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["flag", b"flag", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flag", b"flag", "name", b"name", "token", b"token", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessInstanceList: _TypeAlias = ProcessInstanceList  # noqa: Y015

@_typing.final
class BootRequest(_message.Message):
    """Boot request"""

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    PROCESS_DESCRIPTION_FIELD_NUMBER: _builtins.int
    PROCESS_RESTRICTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> Global___Token: ...
    @_builtins.property
    def process_description(self) -> Global___ProcessDescription: ...
    @_builtins.property
    def process_restriction(self) -> Global___ProcessRestriction: ...
    def __init__(
        self,
        *,
        token: Global___Token | None = ...,
        process_description: Global___ProcessDescription | None = ...,
        process_restriction: Global___ProcessRestriction | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BootRequest: _TypeAlias = BootRequest  # noqa: Y015

@_typing.final
class UpdateRequest(_message.Message):
    """Manager-RootController communication messages"""

    DESCRIPTOR: _descriptor.Descriptor

    UPDATE_TYPE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    SEQUENCE_NUMBER_FIELD_NUMBER: _builtins.int
    update_type: _builtins.str
    content: _builtins.str
    sequence_number: _builtins.int
    def __init__(
        self,
        *,
        update_type: _builtins.str = ...,
        content: _builtins.str = ...,
        sequence_number: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "sequence_number", b"sequence_number", "update_type", b"update_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateRequest: _TypeAlias = UpdateRequest  # noqa: Y015

@_typing.final
class UpdateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACKNOWLEDGED_FIELD_NUMBER: _builtins.int
    RESPONSE_MESSAGE_FIELD_NUMBER: _builtins.int
    acknowledged: _builtins.bool
    response_message: _builtins.str
    def __init__(
        self,
        *,
        acknowledged: _builtins.bool = ...,
        response_message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acknowledged", b"acknowledged", "response_message", b"response_message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateResponse: _TypeAlias = UpdateResponse  # noqa: Y015

@_typing.final
class CommandRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_TYPE_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    COMMAND_ID_FIELD_NUMBER: _builtins.int
    command_type: _builtins.str
    parameters: _builtins.str
    command_id: _builtins.int
    def __init__(
        self,
        *,
        command_type: _builtins.str = ...,
        parameters: _builtins.str = ...,
        command_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_id", b"command_id", "command_type", b"command_type", "parameters", b"parameters"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommandRequest: _TypeAlias = CommandRequest  # noqa: Y015

@_typing.final
class CommandResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    result: _builtins.str
    error_message: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        result: _builtins.str = ...,
        error_message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error_message", b"error_message", "result", b"result", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommandResponse: _TypeAlias = CommandResponse  # noqa: Y015

@_typing.final
class StatusRequest(_message.Message):
    """RootController-ChildController communication messages"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetricsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CONTROLLER_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    METRICS_FIELD_NUMBER: _builtins.int
    controller_id: _builtins.str
    status: _builtins.str
    @_builtins.property
    def metrics(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        controller_id: _builtins.str = ...,
        status: _builtins.str = ...,
        metrics: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["controller_id", b"controller_id", "metrics", b"metrics", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusRequest: _TypeAlias = StatusRequest  # noqa: Y015

@_typing.final
class StatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RECEIVED_FIELD_NUMBER: _builtins.int
    ACKNOWLEDGEMENT_FIELD_NUMBER: _builtins.int
    received: _builtins.bool
    acknowledgement: _builtins.str
    def __init__(
        self,
        *,
        received: _builtins.bool = ...,
        acknowledgement: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acknowledgement", b"acknowledgement", "received", b"received"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusResponse: _TypeAlias = StatusResponse  # noqa: Y015

@_typing.final
class KillRequest(_message.Message):
    """Shutdown/kill functionality messages (custom for test simplicity)"""

    DESCRIPTOR: _descriptor.Descriptor

    REASON_FIELD_NUMBER: _builtins.int
    GRACE_PERIOD_SECONDS_FIELD_NUMBER: _builtins.int
    reason: _builtins.str
    """Reason for shutdown (for logging purposes)"""
    grace_period_seconds: _builtins.int
    """Grace period in seconds before force shutdown"""
    def __init__(
        self,
        *,
        reason: _builtins.str = ...,
        grace_period_seconds: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["grace_period_seconds", b"grace_period_seconds", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KillRequest: _TypeAlias = KillRequest  # noqa: Y015

@_typing.final
class KillResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHUTDOWN_INITIATED_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    shutdown_initiated: _builtins.bool
    """Indicates if the shutdown request was accepted"""
    message: _builtins.str
    """Message describing the shutdown status"""
    def __init__(
        self,
        *,
        shutdown_initiated: _builtins.bool = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "shutdown_initiated", b"shutdown_initiated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KillResponse: _TypeAlias = KillResponse  # noqa: Y015
