"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
import test_services_pb2 as _test_services_pb2
from grpc import aio as _aio

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ManagerServiceStub:
    """Service for Manager component"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ManagerServiceAsyncStub: ...
    MakeRequest: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.DummyRequest, _test_services_pb2.DummyResponse]
    """Basic method for connectivity testing"""
    boot: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.BootRequest, _test_services_pb2.ProcessInstanceList]
    """Boot other processes via the manager"""
    Kill: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.KillRequest, _test_services_pb2.KillResponse]
    """Method for graceful shutdown of the Manager service"""
    ReceiveUpdate: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.UpdateRequest, _test_services_pb2.UpdateResponse]
    """Method for receiving updates from RootController"""

@_typing.type_check_only
class ManagerServiceAsyncStub(ManagerServiceStub):
    """Service for Manager component"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    MakeRequest: _aio.UnaryUnaryMultiCallable[_test_services_pb2.DummyRequest, _test_services_pb2.DummyResponse]  # type: ignore[assignment]
    """Basic method for connectivity testing"""
    boot: _aio.UnaryUnaryMultiCallable[_test_services_pb2.BootRequest, _test_services_pb2.ProcessInstanceList]  # type: ignore[assignment]
    """Boot other processes via the manager"""
    Kill: _aio.UnaryUnaryMultiCallable[_test_services_pb2.KillRequest, _test_services_pb2.KillResponse]  # type: ignore[assignment]
    """Method for graceful shutdown of the Manager service"""
    ReceiveUpdate: _aio.UnaryUnaryMultiCallable[_test_services_pb2.UpdateRequest, _test_services_pb2.UpdateResponse]  # type: ignore[assignment]
    """Method for receiving updates from RootController"""

class ManagerServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service for Manager component"""

    @_abc_1.abstractmethod
    def MakeRequest(
        self,
        request: _test_services_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.DummyResponse, _abc.Awaitable[_test_services_pb2.DummyResponse]]:
        """Basic method for connectivity testing"""

    @_abc_1.abstractmethod
    def boot(
        self,
        request: _test_services_pb2.BootRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.ProcessInstanceList, _abc.Awaitable[_test_services_pb2.ProcessInstanceList]]:
        """Boot other processes via the manager"""

    @_abc_1.abstractmethod
    def Kill(
        self,
        request: _test_services_pb2.KillRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.KillResponse, _abc.Awaitable[_test_services_pb2.KillResponse]]:
        """Method for graceful shutdown of the Manager service"""

    @_abc_1.abstractmethod
    def ReceiveUpdate(
        self,
        request: _test_services_pb2.UpdateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.UpdateResponse, _abc.Awaitable[_test_services_pb2.UpdateResponse]]:
        """Method for receiving updates from RootController"""

def add_ManagerServiceServicer_to_server(servicer: ManagerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class RootControllerServiceStub:
    """Service for RootController component (for testing connectivity to booted servers)"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RootControllerServiceAsyncStub: ...
    MakeRequest: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.DummyRequest, _test_services_pb2.DummyResponse]
    """Basic method for connectivity testing"""
    Kill: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.KillRequest, _test_services_pb2.KillResponse]
    """Method for graceful shutdown"""
    ReceiveCommand: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.CommandRequest, _test_services_pb2.CommandResponse]
    """Method for receiving commands from Manager"""
    ReceiveStatus: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.StatusRequest, _test_services_pb2.StatusResponse]
    """Method for receiving status from ChildControllers"""

@_typing.type_check_only
class RootControllerServiceAsyncStub(RootControllerServiceStub):
    """Service for RootController component (for testing connectivity to booted servers)"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    MakeRequest: _aio.UnaryUnaryMultiCallable[_test_services_pb2.DummyRequest, _test_services_pb2.DummyResponse]  # type: ignore[assignment]
    """Basic method for connectivity testing"""
    Kill: _aio.UnaryUnaryMultiCallable[_test_services_pb2.KillRequest, _test_services_pb2.KillResponse]  # type: ignore[assignment]
    """Method for graceful shutdown"""
    ReceiveCommand: _aio.UnaryUnaryMultiCallable[_test_services_pb2.CommandRequest, _test_services_pb2.CommandResponse]  # type: ignore[assignment]
    """Method for receiving commands from Manager"""
    ReceiveStatus: _aio.UnaryUnaryMultiCallable[_test_services_pb2.StatusRequest, _test_services_pb2.StatusResponse]  # type: ignore[assignment]
    """Method for receiving status from ChildControllers"""

class RootControllerServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service for RootController component (for testing connectivity to booted servers)"""

    @_abc_1.abstractmethod
    def MakeRequest(
        self,
        request: _test_services_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.DummyResponse, _abc.Awaitable[_test_services_pb2.DummyResponse]]:
        """Basic method for connectivity testing"""

    @_abc_1.abstractmethod
    def Kill(
        self,
        request: _test_services_pb2.KillRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.KillResponse, _abc.Awaitable[_test_services_pb2.KillResponse]]:
        """Method for graceful shutdown"""

    @_abc_1.abstractmethod
    def ReceiveCommand(
        self,
        request: _test_services_pb2.CommandRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.CommandResponse, _abc.Awaitable[_test_services_pb2.CommandResponse]]:
        """Method for receiving commands from Manager"""

    @_abc_1.abstractmethod
    def ReceiveStatus(
        self,
        request: _test_services_pb2.StatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.StatusResponse, _abc.Awaitable[_test_services_pb2.StatusResponse]]:
        """Method for receiving status from ChildControllers"""

def add_RootControllerServiceServicer_to_server(servicer: RootControllerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class ChildControllerServiceStub:
    """Service for ChildController components"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ChildControllerServiceAsyncStub: ...
    MakeRequest: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.DummyRequest, _test_services_pb2.DummyResponse]
    """Basic method for connectivity testing"""
    Kill: _grpc.UnaryUnaryMultiCallable[_test_services_pb2.KillRequest, _test_services_pb2.KillResponse]
    """Method for graceful shutdown of the ChildController service"""

@_typing.type_check_only
class ChildControllerServiceAsyncStub(ChildControllerServiceStub):
    """Service for ChildController components"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    MakeRequest: _aio.UnaryUnaryMultiCallable[_test_services_pb2.DummyRequest, _test_services_pb2.DummyResponse]  # type: ignore[assignment]
    """Basic method for connectivity testing"""
    Kill: _aio.UnaryUnaryMultiCallable[_test_services_pb2.KillRequest, _test_services_pb2.KillResponse]  # type: ignore[assignment]
    """Method for graceful shutdown of the ChildController service"""

class ChildControllerServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service for ChildController components"""

    @_abc_1.abstractmethod
    def MakeRequest(
        self,
        request: _test_services_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.DummyResponse, _abc.Awaitable[_test_services_pb2.DummyResponse]]:
        """Basic method for connectivity testing"""

    @_abc_1.abstractmethod
    def Kill(
        self,
        request: _test_services_pb2.KillRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_test_services_pb2.KillResponse, _abc.Awaitable[_test_services_pb2.KillResponse]]:
        """Method for graceful shutdown of the ChildController service"""

def add_ChildControllerServiceServicer_to_server(servicer: ChildControllerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
