# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import drunc.communication.process_manager_pb2 as process__manager__pb2


class ProcessManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Boot = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/Boot',
                request_serializer=process__manager__pb2.BootRequest.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessUUID.FromString,
                )
        self.Resurrect = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/Resurrect',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.IsAlive = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/IsAlive',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.Kill = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/Kill',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.Poll = channel.unary_stream(
                '/DUNEProcessManager.ProcessManager/Poll',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )


class ProcessManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Boot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resurrect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Poll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Boot': grpc.unary_unary_rpc_method_handler(
                    servicer.Boot,
                    request_deserializer=process__manager__pb2.BootRequest.FromString,
                    response_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
            ),
            'Resurrect': grpc.unary_unary_rpc_method_handler(
                    servicer.Resurrect,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'IsAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAlive,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'Poll': grpc.unary_stream_rpc_method_handler(
                    servicer.Poll,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DUNEProcessManager.ProcessManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Boot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/Boot',
            process__manager__pb2.BootRequest.SerializeToString,
            process__manager__pb2.ProcessUUID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Resurrect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/Resurrect',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/IsAlive',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/Kill',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Poll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DUNEProcessManager.ProcessManager/Poll',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
