# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import drunc.communication.process_manager_pb2 as process__manager__pb2


class ProcessManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.boot = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/boot',
                request_serializer=process__manager__pb2.BootRequest.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessUUID.FromString,
                )
        self.resurrect = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/resurrect',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.restart = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/restart',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.is_alive = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/is_alive',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.kill = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/kill',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.poll = channel.unary_stream(
                '/DUNEProcessManager.ProcessManager/poll',
                request_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstance.FromString,
                )
        self.list_process = channel.unary_unary(
                '/DUNEProcessManager.ProcessManager/list_process',
                request_serializer=process__manager__pb2.ProcessMetadata.SerializeToString,
                response_deserializer=process__manager__pb2.ProcessInstanceList.FromString,
                )


class ProcessManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def boot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def resurrect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def restart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_alive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def poll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'boot': grpc.unary_unary_rpc_method_handler(
                    servicer.boot,
                    request_deserializer=process__manager__pb2.BootRequest.FromString,
                    response_serializer=process__manager__pb2.ProcessUUID.SerializeToString,
            ),
            'resurrect': grpc.unary_unary_rpc_method_handler(
                    servicer.resurrect,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'restart': grpc.unary_unary_rpc_method_handler(
                    servicer.restart,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'is_alive': grpc.unary_unary_rpc_method_handler(
                    servicer.is_alive,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'kill': grpc.unary_unary_rpc_method_handler(
                    servicer.kill,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'poll': grpc.unary_stream_rpc_method_handler(
                    servicer.poll,
                    request_deserializer=process__manager__pb2.ProcessUUID.FromString,
                    response_serializer=process__manager__pb2.ProcessInstance.SerializeToString,
            ),
            'list_process': grpc.unary_unary_rpc_method_handler(
                    servicer.list_process,
                    request_deserializer=process__manager__pb2.ProcessMetadata.FromString,
                    response_serializer=process__manager__pb2.ProcessInstanceList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DUNEProcessManager.ProcessManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def boot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/boot',
            process__manager__pb2.BootRequest.SerializeToString,
            process__manager__pb2.ProcessUUID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def resurrect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/resurrect',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def restart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/restart',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_alive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/is_alive',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/kill',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def poll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DUNEProcessManager.ProcessManager/poll',
            process__manager__pb2.ProcessUUID.SerializeToString,
            process__manager__pb2.ProcessInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list_process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUNEProcessManager.ProcessManager/list_process',
            process__manager__pb2.ProcessMetadata.SerializeToString,
            process__manager__pb2.ProcessInstanceList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
