# This workflow checks for __init__.py files in directories and subdirectories.
# Directories missing __init__.py files are needed by mkddocstrings to generate
# documentation from python docstrings
name: Check for __init__.py files

on: 
  pull_request:

jobs:
  check-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Look for __init__ files
        run: |
          missing=$(find src -mindepth 1 \
            \( -path "src/.git*" \-o \
            -path "src/.github*" -o \
            -path "src/tests*" -o \
            -path "src/docs*" -o \
            -path "src/config*" -o \
            -path "src/drunc/integtest*" -o \
            -path "src/drunc/data*" \) -prune -o \
            -type d -exec sh -c '[ ! -e "$1/__init__.py" ] && echo "$1"' _ {} \;)

          if [ -n "$missing" ]; then
            echo "These directories are missing __init__.py:"
            echo "$missing"
            exit 1
          else
            echo "All directories contain __init__.py"
          fi