name: Deploy Docs and Wiki to Pages 
on:
  workflow_dispatch: # enable manual triger. Only works in 'develop' branch 
  workflow_call:
  schedule:
    - cron: "0 0 * * 6" # midnight every Saturday
  gollum:

jobs: 
  docs: 
    timeout-minutes: 15 
    runs-on: ubuntu-latest 
    env: 
      WIKI_SUBFOLDER: Developer-Wiki
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v5

      # Clone the Wiki content  
      - name: Checkout Wiki Content 
        uses: actions/checkout@v5 
        with: 
          repository: ${{ github.repository }}.wiki 
          ref: master # Wiki default branch 
          # Create temporary wiki subfolder
          path: docs/${{ env.WIKI_SUBFOLDER }}

      # Move Archives to a temp folder so they aren't processed
      - name: Hide Archive files from script
        run: |
          mkdir -p /tmp/wiki_archives
          find docs/${{ env.WIKI_SUBFOLDER }} -name "Archive:*" -exec mv {} /tmp/wiki_archives/ \;

      # Copy images from main docs to the wiki folder
      - name: Stage Images for Wiki
        run: |
          cp docs/*.png docs/${{ env.WIKI_SUBFOLDER }}/ || true

      - name: Convert WikiLinks to Markdown Links
        env:
          GITHUB_PAGES_BASE: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
        run: |
          python docs/utils/process_wiki.py $GITHUB_PAGES_BASE $WIKI_SUBFOLDER
          cd ~

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install .

      - name: Deploy Docs
        run: mkdocs gh-deploy --force

      # Check whether the links used in the documentation are valid
      # twiki amd dunescience excludes are used as they are behind SSOs, leading to timeouts, and errors being thrown by this step
      # drunc contains a set of outdated documentation page that should be kept for reference, they contain good descriptions on e.g. configuration structure
      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --exclude 'https://twiki.cern.ch/.*' 
            --exclude 'https://github.com/DUNE-DAQ/drunc/wiki/Archive:.*'
            --exclude 'https://wiki.dunescience.org/wiki/.*'
            docs/