name: Run CVMFS check with additional CVMFS mount

on:
  pull_request:

jobs:
  check_live_cvmfs:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mount LIVE CVMFS on Host
        uses: cvmfs-contrib/github-action-cvmfs@72f2a8d366043978d6aebee154bc9ed321c2f2a8
        with:
          cvmfs_repositories: 'dunedaq.opensciencegrid.org,dunedaq-development.opensciencegrid.org'

      - name: Pull container image
        run: docker pull ghcr.io/dune-daq/nightly-release-alma9:development_v5

      - name: Run Checks on Live CVMFS Mount
        run: |
          cat << 'EOF' > ${GITHUB_WORKSPACE}/check_live_cvmfs.sh
          #!/bin/bash
          echo "=== Installing SQLite ==="
          dnf install -y sqlite
          
          echo "=== Check the base path and its creation date ==="
          echo "Check root"
          ls -l --time-style=full-iso /
          echo "Check /cvmfs"
          ls -l --time-style=full-iso /cvmfs/
          echo "Check DB path"
          ls -l --time-style=full-iso /cvmfs/dunedaq.opensciencegrid.org/assets/dunedaq-asset-db.sqlite
          echo "=== End of Base Path and DB Check ==="
          
          echo "=== Check the asset files in /cvmfs ==="
          DB_PATH="/cvmfs/dunedaq.opensciencegrid.org/assets/dunedaq-asset-db.sqlite"
          
          echo "=== PROOF OF DATABASE LAYER TIMESTAMP ==="
          ls -l --time-style=full-iso "$DB_PATH"
          
          echo "Total rows in DB:"
          sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM dunedaq_assets;"
          
          echo "=== LIVE ASSETS LIST (subsystem=readout) ==="
          sqlite3 -header -column "$DB_PATH" "
            SELECT 
              checksum, 
              subsystem, 
              label, 
              status, 
              '/cvmfs/dunedaq.opensciencegrid.org/assets/' || path || '/' || name AS file_path 
            FROM dunedaq_assets 
            WHERE subsystem='readout';
          "
          echo "=== End of Asset Files Check ==="
          EOF
          
          chmod +x ${GITHUB_WORKSPACE}/check_live_cvmfs.sh
          
          # We add --user root just to guarantee dnf has installation privileges 
          docker run --rm \
            --user root \
            -v /cvmfs:/cvmfs:shared \
            -v "${GITHUB_WORKSPACE}:/ghw" \
            -w /ghw \
            ghcr.io/dune-daq/nightly-release-alma9:development_v5 \
            /ghw/check_live_cvmfs.sh