name: Update GitHub Pages DOCs
on:
  workflow_call:
  schedule:
    - cron: "0 0 * * 1" # midnight every Monday
jobs:
  docs:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: |
              pyproject.toml
              requirements-doc.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install .
      - name: Deploy Docs
        run: mkdocs gh-deploy --force